-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    id integer NOT NULL DEFAULT nextval('clientes_id_seq'::regclass),
    id_banco integer NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    apellido character varying COLLATE pg_catalog."default" NOT NULL,
    documento character varying COLLATE pg_catalog."default" NOT NULL,
    direccion character varying COLLATE pg_catalog."default" NOT NULL,
    mail character varying COLLATE pg_catalog."default" NOT NULL,
    celular character varying COLLATE pg_catalog."default" NOT NULL,
    estado character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT clientes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detalle_factura
(
    id integer NOT NULL,
    id_factura integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad_producto numeric NOT NULL,
    subtotal numeric NOT NULL,
    CONSTRAINT detalle_factura_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detalle_pedido
(
    id integer NOT NULL DEFAULT nextval('detalle_pedido_id_seq'::regclass),
    id_pedido integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad_producto integer NOT NULL,
    subtotal integer NOT NULL,
    CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.facturas
(
    id integer NOT NULL DEFAULT nextval('facturas_id_seq'::regclass),
    id_cliente integer NOT NULL,
    nro_factura character varying COLLATE pg_catalog."default" NOT NULL,
    fecha_hora date NOT NULL,
    total integer NOT NULL,
    total_iva5 character varying COLLATE pg_catalog."default" NOT NULL,
    total_iva10 character varying COLLATE pg_catalog."default" NOT NULL,
    total_iva character varying COLLATE pg_catalog."default" NOT NULL,
    total_letras character varying COLLATE pg_catalog."default" NOT NULL,
    sucursal character varying COLLATE pg_catalog."default" NOT NULL,
    id_sucursal integer NOT NULL,
    CONSTRAINT facturas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pedido_compra
(
    id integer NOT NULL DEFAULT nextval('pedido_compra_id_seq'::regclass),
    id_proveedor integer NOT NULL,
    id_sucursal integer NOT NULL,
    fecha_hora date NOT NULL,
    total integer NOT NULL,
    CONSTRAINT pedido_compra_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id integer NOT NULL DEFAULT nextval('productos_id_seq'::regclass),
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cantidad_minima integer NOT NULL,
    cantidad_stock integer NOT NULL,
    precio_compra integer NOT NULL,
    precio_venta numeric NOT NULL,
    categoria character varying COLLATE pg_catalog."default" NOT NULL,
    marca character varying COLLATE pg_catalog."default" NOT NULL,
    estado character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT productos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proveedor
(
    id integer NOT NULL DEFAULT nextval('proveedor_id_seq'::regclass),
    razon_social integer NOT NULL,
    tipo_doc character varying COLLATE pg_catalog."default" NOT NULL,
    numero_doc integer NOT NULL,
    direccion character varying COLLATE pg_catalog."default" NOT NULL,
    mail character varying COLLATE pg_catalog."default" NOT NULL,
    celular character varying COLLATE pg_catalog."default" NOT NULL,
    estado character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT proveedor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sucursal
(
    id integer NOT NULL,
    descripcion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(50) COLLATE pg_catalog."default" NOT NULL,
    whatsapp character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mail character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sucursal_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.detalle_factura
    ADD CONSTRAINT id_factura FOREIGN KEY (id_factura)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.detalle_factura
    ADD CONSTRAINT id_producto FOREIGN KEY (id_producto)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT id_pedido FOREIGN KEY (id_pedido)
    REFERENCES public.pedido_compra (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT id_producto FOREIGN KEY (id_producto)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.facturas
    ADD CONSTRAINT id_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.facturas
    ADD CONSTRAINT id_sucursal FOREIGN KEY (id_sucursal)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pedido_compra
    ADD CONSTRAINT id_proveedor FOREIGN KEY (id_proveedor)
    REFERENCES public.proveedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
